library(tidyverse)
library(raster)
library(sf)
library(car)
library(tidycensus)
library(lme4)
library(ROCR)
library(MuMIn)

City_name <- "Grand_Rapids"
counties <- c('Ottawa', 'Muskegon', 'Allegan', 'Kent')
geoids <- c(26005,26081,26121,26139)
statefp <- '26'

setwd('D:/GLISA-WWA/Data/GLISA/big_rasters')
NLCD_2001 <- raster("NLCD_2001_GLISA.tif")
NLCD_2004 <- raster("NLCD_2004_GLISA.tif")
NLCD_2006 <- raster("NLCD_2006_GLISA.tif")
NLCD_2008 <- raster("NLCD_2008_GLISA.tif")
NLCD_2011 <- raster("NLCD_2011_GLISA.tif")
NLCD_2013 <- raster("NLCD_2013_GLISA.tif")
NLCD_2016 <- raster("NLCD_2016_GLISA.tif")
GEOID <- raster("GEOID.tif")
#NLCDChg_2016<- raster("ChgNLCD_GLISA16.tif")

Roads <- raster("Roads_GLISA.tif")
Protect <- raster("IUNCprotect_GLISA_reproject_cellalign.tif")

Floodplain <- raster("Floodplain_GLISA.tif")
Cost_dist<- raster("GLISA_costdist.tif")
DEM<- raster("DEM_GLISA.tif")
GL_dist <- raster("Dist_GL.tif")
WB_dist <- raster("Dist_WB.tif")
Canopy<- raster("Canopy2011.tif")
Canopy2016 <- raster("Canopy2016GLISA.tif")
OvPass <- raster("distanceOvPass.tif")
protectArea_dist <- raster("Glisa_distProt.tif")
schooldist <- raster("public_school_dist_m.tif") #distance in m
histdist <- raster("GLISA_buildings.tif")

# Shapefile of GLISA area counties that we load with SF
County <- read_sf("GLISA_county.shp")

# Development pressure generated by FUTUREs model in GRASS GIS (default settings)
devpressure_def <- raster("devpressure_def_2001.tif")
devpressure_big <- raster("devpressure_big_2001.tif")
devpressure_med <- raster("devpressure_med_2001.tif")
devpressure_occ <- raster("devpressure_occ_2001.tif")

# Stack together
allrasters <- stack(NLCD_2001, NLCD_2004, NLCD_2006, NLCD_2008, NLCD_2011, NLCD_2013, NLCD_2016, GEOID, Floodplain, Cost_dist, DEM, WB_dist, GL_dist, Canopy, Canopy2016, OvPass, Roads, Protect, protectArea_dist, schooldist, histdist, devpressure_def, devpressure_big, devpressure_med, devpressure_occ)

# Clip
mask <- County %>%
  filter(NAME %in% counties & STATEFP == statefp)  
cropped <- crop(x = allrasters, y = extent(mask))
maskStack <- mask(cropped, mask)

# Clear unneeded variables
rm(NLCD_2001, NLCD_2004, NLCD_2006, NLCD_2008, NLCD_2011, NLCD_2013, NLCD_2016, GEOID, Floodplain, Cost_dist, DEM, GL_dist, WB_dist, Canopy, Canopy2016, OvPass, protectArea_dist, schooldist, histdist, County, devpressure_def, devpressure_big, devpressure_med, devpressure_occ, allrasters, cropped, mask)

#################################################################################################################

setwd('D:/GLISA-WWA/Data/GLISA/by_city')

gc() 

allrasters <- as.data.frame(maskStack) 

allrasters <- allrasters %>%
  filter(is.na(IUNCprotect_GLISA_reproject_cellalign)) %>%
  dplyr::select(!IUNCprotect_GLISA_reproject_cellalign)

allrasters <- na.omit(allrasters) %>%
  filter(Roads_GLISA != 1) %>%
  dplyr::select(!Roads_GLISA)

summary(allrasters)

allrasters$OvPass_resc <- allrasters$distanceOvPass/1000 # to km
allrasters$GL_dist_resc <- allrasters$Dist_GL/1000 # to km
allrasters$WB_dist_resc <- allrasters$Dist_WB/100 
allrasters$Cost_dist_resc <- allrasters$GLISA_costdist/36000 # to hours
allrasters$GLISA_buildings_resc <- allrasters$GLISA_buildings/1000 # to km
allrasters$Glisa_distProt_resc <- allrasters$Glisa_distProt/10 
allrasters$public_school_dist_m_resc <- allrasters$public_school_dist_m/100


# Developed
allrasters$newUrb <- ifelse((!(allrasters$NLCD_2001_GLISA %in% c(21,22,23,24)) & (allrasters$NLCD_2016_GLISA %in% c(21,22,23,24))), 1, 0)

devcount <- sum(allrasters$newUrb)

allrasters$newUrb <- as.factor(allrasters$newUrb)
allrasters$Floodplain_GLISA <- as.factor(allrasters$Floodplain_GLISA)
allrasters$GEOID <- as.factor(allrasters$GEOID)

#############################################################
### Training/testing ########################################
#############################################################

set.seed(1)
ones <- allrasters %>%
  filter(newUrb == 1)
onesize <- floor(nrow(ones)/2)
zerosize <- onesize*2

zeros <- allrasters %>% # developable; non-urban
  filter((newUrb == 0) & !(NLCD_2001_GLISA %in% c(11,21,22,23,24,90,95)))

index1 <- sample(1:nrow(ones), size=onesize)
Ones_train <- ones[index1, ]
Ones_test <- ones[-index1, ]

index0 <- sample(1:nrow(zeros), size=zerosize)
Zero_train <- zeros[index0, ]
Zero_test <- zeros[-index0, ]
index0_2 <- sample(1:nrow(Zero_test), size=zerosize*2)
Zero_test <- Zero_test[index0_2, ]

train_sample <- rbind(Ones_train, Zero_train)
test_sample <- rbind(Ones_test, Zero_test)
test_labels_newUrb <- test_sample$newUrb

rm(ones)
rm(zeros)
rm(onesize)
rm(zerosize)
rm(index1)
rm(index0)
rm(Zero_test)
rm(Zero_train)
rm(Ones_train)
rm(Ones_test)
#rm(region_data) #if needed
gc()

# model_newurb <- glmer(newUrb ~ devpressure_def_2001 + devpressure_big_2001 + devpressure_med_2001 + devpressure_occ_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
#                       data = train_sample,
#                       family = binomial(link="logit"),
#                       na.action = 'na.fail',
#                       control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
# summary(model_newurb)
# 
# vif(model_newurb)
# 
# mod_select <- dredge(model_newurb, beta = "none", fixed=c('Floodplain_GLISA'), trace = 2)
# write.csv(mod_select, "model_selectGLISA.csv")

model_newurb_def <- glmer(newUrb ~ devpressure_def_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                      data = train_sample,
                      family = binomial(link="logit"),
                      na.action = 'na.fail',
                      control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_def <- dredge(model_newurb_def, beta = "none", fixed=c('Floodplain_GLISA', 'devpressure_def_2001'), trace = 2)
write.csv(mod_select_def, "model_select_def_GLISA2.csv")

model_newurb_big <- glmer(newUrb ~ devpressure_big_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_big <- dredge(model_newurb_big, beta = "none", fixed=c('Floodplain_GLISA', 'devpressure_big_2001'), trace = 2)
write.csv(mod_select_big, "model_select_big_GLISA2.csv")

model_newurb_med <- glmer(newUrb ~ devpressure_med_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_med <- dredge(model_newurb_med, beta = "none", fixed=c('Floodplain_GLISA', 'devpressure_med_2001'), trace = 2)
write.csv(mod_select_med, "model_select_med_GLISA2.csv")

model_newurb_occ <- glmer(newUrb ~ devpressure_occ_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_occ <- dredge(model_newurb_occ, beta = "none", fixed=c('Floodplain_GLISA', 'devpressure_occ_2001'), trace = 2)
write.csv(mod_select_occ, "model_select_occ_GLISA2.csv")
#############################################################

model_newurb_def_reduced <- glmer(newUrb ~ devpressure_def_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
vif(model_newurb_def_reduced)

model_newurb_big_reduced <- glmer(newUrb ~ devpressure_big_2001.Devpressure + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
vif(model_newurb_big_reduced)

model_newurb_med_reduced <- glmer(newUrb ~ devpressure_med_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
vif(model_newurb_med_reduced)

model_newurb_occ_reduced <- glmer(newUrb ~ devpressure_occ_2001 + Cost_dist_resc + DEM_GLISA + WB_dist_resc + GL_dist_resc + Canopy2016GLISA + OvPass_resc + Glisa_distProt_resc + Floodplain_GLISA + public_school_dist_m_resc + GLISA_buildings_resc + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
vif(model_newurb_occ_reduced)



###############################################
# Accuracy Testing

prediction_test <- predict(model_newurb_def_reduced, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_def <- performance(pred, measure="auc")
print(auc.perf_def@y.values)


prediction_test <- predict(model_newurb_big_reduced, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_big <- performance(pred, measure="auc")
print(auc.perf_big@y.values)

prediction_test <- predict(model_newurb_med_reduced, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_med <- performance(pred, measure="auc")
print(auc.perf_med@y.values)

prediction_test <- predict(model_newurb_occ_reduced, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_occ <- performance(pred, measure="auc")
print(auc.perf_occ@y.values)



setwd('D:/GLISA-WWA/Paper_runs/Grand_rapids')

write_csv(as.data.frame(coef(model_newurb_big_reduced)[[1]]), paste0(City_name, "_ss_round3.csv"))


## Standardized beta coefficients

model_newurb_big_reduced_std <- glmer(newUrb ~ scale(devpressure_big_2001.Devpressure) + scale(Cost_dist_resc) + scale(DEM_GLISA) + scale(WB_dist_resc) + scale(GL_dist_resc) + scale(Canopy2016GLISA) + scale(OvPass_resc) + scale(Glisa_distProt_resc) + Floodplain_GLISA + scale(public_school_dist_m_resc) + scale(GLISA_buildings_resc) + (1 | GEOID),
                                  data = train_sample,
                                  family = binomial(link="logit"),
                                  na.action = 'na.fail',
                                  control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
summary(model_newurb_big_reduced_std)

saveRDS(model_newurb_big_reduced, file='GR_model.rds')
saveRDS(model_newurb_big_reduced_std, file='GR_model_standardized.rds')









