library(dplyr)
library(tidyr)
library(raster)
library(sf)
library(car)
library(lme4)
library(ROCR)
library(MuMIn)

City_name <- "CS_Pueblo"
# counties <- c('Teller', 'El Paso', 'Fremont', 'Pueblo')
# geoids <- c(103,101,35,21) #weird mis-coded GEOID raster
counties <- c('Teller', 'El Paso', 'Pueblo')
geoids <- c(103,101,21) #weird mis-coded GEOID raster
statefp <- '08'



setwd('D:/GLISA-WWA/Data/WWA/big_rasters')
NLCD_2001 <- raster("WWA_NLCD_01.tif")
NLCD_2016 <- raster("WWA_NLCD_16.tif")
GEOID <- raster("GEOID.tif")
#NLCDChg_2016<- raster("ChgNLCD_WWA16.tif")

Roads <- raster("Roads_WWA.tif")
protect <- raster("IUNCprotect_WWA3.tif")

Floodplain <- raster("Floodplain.tif")
Cost_dist<- raster("Cst_dst_WWA.tif")
DEM<- raster("DEM_WWA.tif")
WB_dist <- raster("DistWater.tif")
Canopy2016 <- raster("Canopy2016.tif")
OvPass <- raster("OvPass.tif")
protectArea_dist <- raster("Protect_WWA2.tif")
schooldist <- raster("public_school_dist.tif") #distance in meters
histdist <- raster("WWA_buildings.tif")
slope <- raster("Slope_WWA.tif")
wildfire <- raster("RPS_wildfire_reproject.tif") #https://www.fs.usda.gov/rds/archive/Catalog/RDS-2020-0016

# Shapefile of GLISA area counties that we load with SF
County <- read_sf("GEOID2.shp")

# Development pressure generated by FUTUREs model in GRASS GIS (default settings)
devpressure_def <- raster("devpressure_def_2001.tif")
devpressure_big <- raster("devpressure_big_2001.tif")
devpressure_med <- raster("devpressure_med_2001.tif")
devpressure_occ <- raster("devpressure_occ_2001.tif")

# Stack together
allrasters <- stack(NLCD_2001, NLCD_2016, GEOID, Floodplain, Cost_dist, DEM, WB_dist, Canopy2016, OvPass, Roads, protectArea_dist, schooldist, histdist, slope, devpressure_def, devpressure_big, devpressure_med, devpressure_occ, protect, wildfire)

# Clip
mask <- County %>%
  filter(NAME %in% counties & STATEFP == statefp)  
cropped <- crop(x = allrasters, y = extent(mask))
maskStack <- mask(cropped, mask)

# Clear unneeded variables
rm(NLCD_2001, NLCD_2016, GEOID, Floodplain, Cost_dist, DEM, slope, WB_dist, Canopy2016, OvPass, protectArea_dist, schooldist, histdist, County, devpressure_def, devpressure_big, devpressure_med, devpressure_occ, allrasters, cropped, mask, protect, wildfire, Roads)

#################################################################################################################

setwd('D:/GLISA-WWA/Data/WWA/by_city')

gc()
allrasters <- as.data.frame(maskStack)
gc()
allrasters <- allrasters %>%
  filter(Roads_WWA != 1) 

gc()
allrasters <- allrasters %>%
  filter(is.na(Band_1)) 

gc()
allrasters <- allrasters %>%
  dplyr::select(!Band_1) %>%
  dplyr::select(!Roads_WWA) %>%
  drop_na() 

allrasters <- allrasters %>% 
  filter(GEOID %in% geoids)

gc()

allrasters$OvPass_resc <- allrasters$OvPass/1000 # to km
allrasters$WB_dist_resc <- allrasters$dist_to_water.PERMANENT/1000 
allrasters$Cost_dist_resc <- allrasters$Cst_dst_WWA/60 # to hours
allrasters$Dist_prot_resc <- allrasters$Protect_WWA2/10 
allrasters$DEM_resc <- allrasters$DEM_WWA/100

allrasters$WWA_buildings_resc <- allrasters$WWA_buildings/1000 # to km
allrasters$public_school_dist_resc <- allrasters$public_school_dist/1000
allrasters$wildfire_resc <- allrasters$RPS_wildfire_reproject*100


# Developed
allrasters$newUrb <- ifelse((!(allrasters$WWA_NLCD_01 %in% c(21,22,23,24)) & (allrasters$WWA_NLCD_16 %in% c(21,22,23,24))), 1, 0)


devcount <- sum(allrasters$newUrb)


allrasters$newUrb <- as.factor(allrasters$newUrb)
allrasters$GEOID <- as.factor(allrasters$GEOID)

gc()
#############################################################
### Training/testing ########################################
#############################################################

set.seed(1)
ones <- allrasters %>%
  filter(newUrb == 1)
onesize <- floor(nrow(ones)/2)
zerosize <- onesize*2

zeros <- allrasters %>% # developable; non-urban
  filter((newUrb == 0) & !(WWA_NLCD_01 %in% c(11,21,22,23,24,90,95)))

index1 <- sample(1:nrow(ones), size=onesize)
Ones_train <- ones[index1, ]
Ones_test <- ones[-index1, ]

index0 <- sample(1:nrow(zeros), size=zerosize)
Zero_train <- zeros[index0, ]
Zero_test <- zeros[-index0, ]
index0_2 <- sample(1:nrow(Zero_test), size=zerosize*2)
Zero_test <- Zero_test[index0_2, ]

train_sample <- rbind(Ones_train, Zero_train)
test_sample <- rbind(Ones_test, Zero_test)
test_labels_newUrb <- test_sample$newUrb

rm(ones)
rm(zeros)
rm(onesize)
rm(zerosize)
rm(index1)
rm(index0)
rm(Zero_test)
rm(Zero_train)
rm(Ones_train)
rm(Ones_test)
#rm(region_data) #if needed
gc()

# model_newurb <- glmer(newUrb ~ devpressure_def_2001 + devpressure_big_2001 + devpressure_med_2001 + devpressure_occ_2001 + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
#                       data = train_sample,
#                       family = binomial(link="logit"),
#                       na.action = 'na.fail',
#                       control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

model_newurb_big <- glmer(newUrb ~ devpressure_big_2001.Devpressure + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                      data = train_sample,
                      family = binomial(link="logit"),
                      na.action = 'na.fail',
                      control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_big <- dredge(model_newurb_big, beta = "none", fixed = c("wildfire_resc", "devpressure_big_2001"), trace = 2)
write.csv(mod_select_big, "model_selectWWA_big2.csv")

model_newurb_def <- glmer(newUrb ~ devpressure_def_2001 + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                      data = train_sample,
                      family = binomial(link="logit"),
                      na.action = 'na.fail',
                      control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_def <- dredge(model_newurb_def, beta = "none", fixed = c("wildfire_resc", "devpressure_def_2001"), trace = 2)
write.csv(mod_select_def, "model_selectWWA_def2.csv")

model_newurb_med <- glmer(newUrb ~ devpressure_med_2001 + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                      data = train_sample,
                      family = binomial(link="logit"),
                      na.action = 'na.fail',
                      control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_med <- dredge(model_newurb_med, beta = "none", fixed = c("wildfire_resc", "devpressure_med_2001"), trace = 2)
write.csv(mod_select_med, "model_selectWWA_med2.csv")


model_newurb_occ <- glmer(newUrb ~ devpressure_occ_2001 + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                      data = train_sample,
                      family = binomial(link="logit"),
                      na.action = 'na.fail',
                      control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
mod_select_occ <- dredge(model_newurb_occ, beta = "none", fixed = c("wildfire_resc", "devpressure_occ_2001"), trace = 2)
write.csv(mod_select_occ, "model_selectWWA_occ2.csv")

#summary(model_newurb)

#vif(model_newurb)

# mod_select <- dredge(model_newurb, beta = "none", fixed = c("wildfire_resc"), trace = 2)
# write.csv(mod_select, "model_selectWWA.csv")

#############################################################

model_newurb_reduced_big <- glmer(newUrb ~ devpressure_big_2001.Devpressure + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                              data = train_sample,
                              family = binomial(link="logit"),
                              na.action = 'na.fail',
                              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(model_newurb_reduced_big)
vif(model_newurb_reduced_big)

model_newurb_reduced_def <- glmer(newUrb ~ devpressure_def_2001 + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                                  data = train_sample,
                                  family = binomial(link="logit"),
                                  na.action = 'na.fail',
                                  control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(model_newurb_reduced_def)
vif(model_newurb_reduced_def)

model_newurb_reduced_med <- glmer(newUrb ~ devpressure_med_2001 + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                                  data = train_sample,
                                  family = binomial(link="logit"),
                                  na.action = 'na.fail',
                                  control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(model_newurb_reduced_med)
vif(model_newurb_reduced_med)

model_newurb_reduced_occ <- glmer(newUrb ~ devpressure_occ_2001 + Cost_dist_resc + DEM_resc + WB_dist_resc + Slope_WWA + Canopy2016 + OvPass_resc + Dist_prot_resc + Floodplain + public_school_dist_resc + WWA_buildings_resc + wildfire_resc + (1 | GEOID),
                                  data = train_sample,
                                  family = binomial(link="logit"),
                                  na.action = 'na.fail',
                                  control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(model_newurb_reduced_occ)
vif(model_newurb_reduced_occ)

setwd('D:/GLISA-WWA/Paper_runs/Colorado_springs')

write.csv(as.data.frame(coef(model_newurb_reduced_big)[[1]]), paste0(City_name, "_ss_round3.csv"))

###############################################
# Accuracy Testing

prediction_test <- predict(model_newurb_reduced_def, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_def <- performance(pred, measure="auc")
print(auc.perf_def@y.values)


prediction_test <- predict(model_newurb_reduced_big, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_big <- performance(pred, measure="auc")
print(auc.perf_big@y.values)

prediction_test <- predict(model_newurb_reduced_med, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_med <- performance(pred, measure="auc")
print(auc.perf_med@y.values)

prediction_test <- predict(model_newurb_reduced_occ, test_sample[,])

pred <- prediction(as.numeric(prediction_test), as.numeric(test_labels_newUrb))
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)

# table(observed=test_labels_newUrb, predicted=prediction_test)
auc.perf_occ <- performance(pred, measure="auc")
print(auc.perf_occ@y.values)

####### Standardized betas
model_newurb_big_std <- glmer(newUrb ~ scale(devpressure_big_2001.Devpressure) + scale(Cost_dist_resc) + scale(DEM_resc) + scale(WB_dist_resc) + scale(Slope_WWA) + scale(Canopy2016) + scale(OvPass_resc) + scale(Dist_prot_resc) + Floodplain + scale(public_school_dist_resc) + scale(WWA_buildings_resc) + scale(wildfire_resc) + (1 | GEOID),
                          data = train_sample,
                          family = binomial(link="logit"),
                          na.action = 'na.fail',
                          control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
summary(model_newurb_big_std)

saveRDS(model_newurb_reduced_big, file='CS_model.rds')
saveRDS(model_newurb_big_std, file='CS_model_standardized.rds')
